### ISSUE TITLE
Attributes Filter checkbox list: product count is read twice

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-blocks#1658]
![imatge](https://user-images.githubusercontent.com/3616980/73258166-6cec2700-41c5-11ea-8111-48e78a3cf15e.png)

**To Reproduce**
1. Create a post with the _All Products_ and _Attribute Filter_ blocks.
2. In _Attribute Filter_ options, select _Display Style_ > _List_.
3. In the frontend and with a screen reader, navigate to the _Attribute Filter_ and activate/deactivate some options.
4. Notice the string `1 product` is read twice when navigating to each option. Which causes unnecessary noise.

**Expected behavior**
Navigating to each option should read the attribute value and the product count only once.

**Comment by ralucaStan** [comment]
I used VoiceOver and could not reproduce the bug. 

It might be that it ignores the first-child span.
```
<span class="wc-block-attribute-filter-list-count">
   <span aria-hidden="true">1</span>
   <span class="screen-reader-text">1 product</span>
</span>
```

@Aljullu can you still reproduce it? What tool did you use?

**Comment by Aljullu** [comment]
I can reproduce it with Orca (only available in Linux). It seems to be an issue with the `float: right` in `.wc-block-attribute-filter-list-count`. When I remove that rule, the count is only read once.

This might be a bug in Orca because nothing in our markup looks wrong to me. However, I guess we can fix/work-around it on our end using flexbox instead of a `float` to align the items?

**Comment by Aljullu** [comment]
Closing as I'm not able to reproduce it anymore.
