### ISSUE TITLE
Ensure integers parsed from API responses are between min/max valid values

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-blocks#1754]
Discussed in https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1559#discussion_r379504588.

In several places around the code base we are parsing integers from the database. This issue is about making sure those values are between `Number.MAX_SAFE_INTEGER` and `Number.MIN_SAFE_INTEGER`.

Some ideas on what to do when the parsed value is outside the min/max valid values:
* Throw an error.
* Return `null` and let consuming components handle that.
* Just return the closest boundary value (`Number.MAX_SAFE_INTEGER` or `Number.MIN_SAFE_INTEGER`).
* Do some magic with [BigInts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt)?

**Comment by mikejolley** [comment]
@Aljullu What are the implications should a number be encountered thats out of bounds? Would it prevent checkout? Or just cause display issues?

BigInt looks promising but it would be nice to only need to use it should bounds be exceeded. Maybe handled via abstraction?

**Comment by Aljullu** [comment]
> What are the implications should a number be encountered thats out of bounds? Would it prevent checkout? Or just cause display issues?

I didn't do a round of testing with our blocks, but in general, numbers greater than the max safe are not accurate and we can't rely on them to do any calculation or to be displayed correctly in the screen.
![imatge](https://user-images.githubusercontent.com/3616980/79986992-26992200-84ad-11ea-8e6e-03d6e909e4e9.png)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER#Description

So all kind of bugs may appear when using numbers out of bounds.

> BigInt looks promising but it would be nice to only need to use it should bounds be exceeded. Maybe handled via abstraction?

That would be really nice. I'm just wary of adding complexity to the codebase for an edge case. Is there a legit case where a store will need to use a number bigger than 9 quadrillion?

**Comment by mikejolley** [comment]
> Is there a legit case where a store will need to use a number bigger than 9 quadrillion?

I'm not sure. Does Dr. Evil use WooCommerce?

Possibly stores using bitcoin/crypto - those generally use larger numbers?

> numbers greater than the max safe are not accurate and we can't rely on them to do any calculation or to be displayed correctly in the screen.

Maybe to satisfy this we return null and add a warning to console. As long as the API side works, payments should not be disrupted.
