### ISSUE TITLE
Single Product Atomic Inner Blocks

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce-blocks#2393]
The single product block requires additional atomic blocks and components to show product data and the full add to cart form experience.

**Comment by garymurray** [comment]
> Product description/short description. The current mocks appear to show a short description. We need to decide how full descriptions are rendered. "additional information" is out of scope for i1, however, description is mentioned. So this needs clarification from @garymurray

The intent was that this would use what has been set as the `Product short description`.

> The designs are missing such as "in stock" text. Does this need revision?

Can you provide a list of what core currently shows there so we can decide how much of that we can/should show? I do believe for instance 'In stock` is something we would want to show.

**Comment by mikejolley** [comment]
> Can you provide a list of what core currently shows there so we can decide how much of that we can/should show? I do believe for instance 'In stock` is something we would want to show.

Wasn't this explored by design team already? 

- Sale badge
- Product title
- Product price (for variable products this is a range)
- Stock text i.e. "In Stock" or "X left in stock"
- Cart qty/button
- SKU
- Terms list (categories and tags)
- Main image
- Image gallery
- Then the full description/attributes/reviews section
- Then related products and upsells

**Comment by garymurray** [comment]
Thanks for those. @LevinMedia this should be able to inform any design work on the single block.

> Wasn't this explored by design team already?

TBH, I am not sure - I had assumed most of this had been taken into account for already in the designs that had been worked on - but now that we taking a closer look at the designs it seems lots might have just been overlooked.

**Comment by LevinMedia** [comment]
@mikejolley @garymurray 

the scope from https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2379 looks correct, I have a few comments to add:

>Product description/short description. The current mocks appear to show a short description. We need to decide how full descriptions are rendered. "additional information" is out of scope for i1, however, description is mentioned.

This should use the short description - the full description is out of scope, and would be built into another block that would be part of a larger product page template, along with reviews etc)

>Core feature parity - The designs are missing such as "in stock" text. Does this need revision?

I think this was overlooked, as I never saw mention of it in the original posts. If it's not too much extra scope, I think it would be nice to have. Likewise, the products SKU, categories and tags would be nice to haves as well. I'm not sure why they weren't included in the original scope. 

If we're able to include all of the above, the only thing we'd be missing for full feature parity with core is gallery controls.

**Comment by LevinMedia** [comment]
@mikejolley FWIW... I think we should also allow columns as an inner block for this thing, but maybe limiting its options to only 2 columns as a start.

**Comment by Aljullu** [comment]
Closing this issue given that we are working on a new version of the Single Product block: https://github.com/woocommerce/woocommerce-blocks/issues/8054. Feel free to reopen if you think that's a mistake. :pray:
