### ISSUE TITLE
All Products: <select> looks different in the editor vs frontend

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-blocks#2506]
Several blocks, like _All Products_, have native `<select>` elements that inherit some styles in the editor (via the selector `.wp-core-ui select`). Those styles are not loaded in the frontend so they look different editor vs frontend.

**Screenshots**
_Editor:_
![imatge](https://user-images.githubusercontent.com/3616980/82303796-ba321580-99bb-11ea-8b5d-aa660d07c3da.png)

_Frontend:_
![imatge](https://user-images.githubusercontent.com/3616980/82303829-c3bb7d80-99bb-11ea-9313-9d670cf23165.png)

_Note: this issue is not about the `<select>` being disabled (see #2487), but about it having different padding, background, border, etc._

**Comment by nerrad** [comment]
Just tested this today and the issue still exists (tested Storefront).

**Comment by tarunvijwani** [comment]
I'd like to work on this.

**Comment by tarunvijwani** [comment]
Waiting for [WordPress/gutenberg#20797](https://github.com/WordPress/gutenberg/issues/20797) to get resolved.

For more information, please check the [PR comment](https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/5973#pullrequestreview-897339248).
