### ISSUE TITLE
Product Price block: alignment options don't work consistently (when `Align last block` is enabled)

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce-blocks#3049]
## To reproduce
1. Add a product price block.
2. In the block toolbar, change the alignment option to center or right.
3. Notice the price stays left-aligned.

### Update (discovered in 3.3.0 testing)
The alignment options don't work when `Align last block` is enabled.

1. Edit a page with an All Products block. Click pencil icon to edit item layout.
2. Add or select a product price block.
2. In the block toolbar, change the alignment option to left or right.
3. Click `Done`.
4. Select the All Products block and toggle the `Align last block` option. 
5. Notice that alignment only works correctly if `Align last block == off`. Issue affects editor preview and front end.

## Screenshots
![Peek 2020-08-25 10-58](https://user-images.githubusercontent.com/3616980/91154672-0fb84580-e6c2-11ea-8b0c-9b389501d28f.gif)

**Comment by haszari** [comment]
Reopening - during 3.3.0 release testing I couldn't get the alignment options to work on the front end with All Products block. The editor behaviour is fixed - i.e. it aligns right/left when editing layout. I'm assuming the expectation is that the alignment options work correctly in front end and in editor preview.

**Comment by haszari** [comment]
Here's a gif showing alignment options working in `All Products` cell layout editor, but not in editor preview:

![Screen Capture on 2020-09-01 at 10-07-08](https://user-images.githubusercontent.com/4167300/91773506-08051d80-ec3b-11ea-8f0c-4ac40d513637.gif)

And this is what that looks like on the front end - note the alignment options don't work:

<img width="992" alt="Screen Shot 2020-09-01 at 10 09 12 AM" src="https://user-images.githubusercontent.com/4167300/91773632-426eba80-ec3b-11ea-95aa-1050ef4847b2.png">

**Comment by Aljullu** [comment]
@haszari I'm unable to reproduce. This is how it looks in the frontend in Storefront and Twenty Twenty for me:

![imatge](https://user-images.githubusercontent.com/3616980/91835106-34c03180-ec49-11ea-9f96-da343d1ed26c.png)
![imatge](https://user-images.githubusercontent.com/3616980/91835064-2b36c980-ec49-11ea-8c87-7af67f62ab25.png)

**Comment by haszari** [comment]
Update! The alignment options work with default settings, but the price is always centered if `Align last block` is enabled. I'v updated title/description above.

![Screen Capture on 2020-09-02 at 11-40-26](https://user-images.githubusercontent.com/4167300/91916436-440ab200-ed11-11ea-820b-4c0fb7191890.gif)

Note I've commandeered this bug since it was already reopened, I'm happy to open a new issue if preferable.

**Comment by Aljullu** [comment]
I noticed I unassigned myself from this issue but it was still in the _In Progress_ pipeline. I moved it to backlog for now.

**Comment by davidhealey** [comment]
It seems there are no alignment options for the price in the latest version and the price will always be centred.

![image](https://user-images.githubusercontent.com/14021202/210466103-f50956f4-b0a7-4b17-bc69-236b3abd61e9.png)

**Comment by Aljullu** [comment]
Thanks for bringing this to our attention, @davidhealey!

@danieldudzic can you check this one? It looks like price alignment used to work in the All Products block, but at some point it broke (and then we removed the option).

**Comment by danieldudzic** [comment]
@Aljullu I'll look into this!
