### ISSUE TITLE
Limit Character Count in Postal Code

### ISSUE THREAD

**Issue by mwailes11** [woocommerce/woocommerce-blocks#3326]
Would love to see the ability to limit the character count in the postal code box. The US Zip +4 causes havoc on our shipping plugin!

**Comment by senadir** [comment]
Thank you for your feedback @mwailes11 
However, I don't see a good reason for limiting it right now, the zipcode length can vary and can reach [12 characters in some countries](https://en.wikipedia.org/wiki/List_of_postal_codes).

There's also no limitation in that field in the shortcode Checkout.

What kind of problems or values are you receiving, we might consider adding more robust validation or the possibility to extend validation for third-party developers.

After I get your feedback, I'm going to either reformat this issue depending on your feedback or close it if we can't address it soon.
Closing an issue doesn't mean we're disregarding your feedback, but we use open issues to track in-progress work that we're working on.

**Comment by mikejolley** [comment]
Woo core (on the php side) has several country specific postcode formats which limit input and format appropriately. We should port this to the client.

**Comment by AashikP** [comment]
Just wanted to add as this looks related. While the checkout block seems to validate the zip correctly, the cart block doesn't:

Build-in cart page when attempting to add incorrect Zipcode (random characters):

![https://d.pr/i/beYwkE+](https://d.pr/i/beYwkE+)

Cart block:

![https://d.pr/i/JDuyb6+](https://d.pr/i/JDuyb6+)

Tested with:

WooCommerce: 6.3.1
WooCommerce Blocks: 7.3.0
