### ISSUE TITLE
Remove experimental "Add to Cart" block

### ISSUE THREAD

**Issue by kmanijak** [woocommerce/woocommerce-blocks#8786]
### Description
Remove the "Add to Cart" Product Element: https://github.com/woocommerce/woocommerce-blocks/tree/trunk/assets/js/atomic/blocks/product-elements/add-to-cart

### Rationale
- it’s [experimental](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/atomic/blocks/product-elements/add-to-cart/index.ts#L26)
- it seems untouched for ~3 years
- there’s new "Add to Cart Form" block which serves the same purpose

**Comment by gigitux** [comment]
Thanks for opening this issue! I agree with you!
It seems that the Cross Sell Product block uses this block ([source code](https://github.com/woocommerce/woocommerce-blocks/blob/321b3d7043b1619a469a3c22e053e336a1a0b5ea/assets/js/blocks/cart/cart-cross-sells-product-list/cart-cross-sells-product.tsx)), but this latter isn’t under the experimental flag. 🤔 
 
Shouldn’t we remove the Add to Cart block? But how does it works currently if the Add to Cart block is available only on the experimental build? 

cc @nielslange that, if I'm not wrong, he worked on the Cross Sell Product block.

**Comment by nielslange** [comment]
> cc @nielslange that, if I'm not wrong, he worked on the Cross Sell Product block.

Thanks for your ping, @gigitux! The Cross-Sell Product block indeed uses the Add to Cart block. Before removing the Add to Cart block, we should adjust the Cross-Sell Product block to use the Add to Cart Form block instead.

@kmanijak I guess removing the Add to Cart block is not urgent, isn't it? I'm asking to know how [Cross-Sells Products block: Replace Add to Cart block with Add to Cart Form block](https://github.com/woocommerce/woocommerce-blocks/issues/8858) should be prioritised.

**Comment by gigitux** [comment]
> > cc @nielslange that, if I'm not wrong, he worked on the Cross Sell Product block.
> 
> Thanks for your ping, @gigitux! The Cross-Sell Product block indeed uses the Add to Cart block. Before removing the Add to Cart block, we should adjust the Cross-Sell Product block to use the Add to Cart Form block instead.
> 
> @kmanijak I guess removing the Add to Cart block is not urgent, isn't it? I'm asking to know how [Cross-Sells Products block: Replace Add to Cart block with Add to Cart Form block](https://github.com/woocommerce/woocommerce-blocks/issues/8858) should be prioritised.

Absolutely! It isn't urgent! Also, I don't know if the Add to Cart Form block can replace the Add to Cart block currently.

But how does it works currently if the Add to Cart block is available only on the experimental build? Should we double-check this?

**Comment by nielslange** [comment]
> @nielslange, keep in mind, the case for Grouped product was never covered and <p>This is a placeholder for the grouped products form element.</p> will be displayed ([source](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/atomic/blocks/product-elements/add-to-cart/product-types/grouped.tsx))

@kmanijak That would be a problem, as it would mean that a grouped product cannot be a Cross-Sells product, right? What Add to Cart buttons do grouped products currently have?

**Comment by wavvves** [comment]
It seems this block uses the SelectControl imported from `wordpress-components` alias which should be removed, and is the only thing consuming it. Removing this block should include work to cleanup that dependency 👍🏼
